#!/bin/sh

COMMON_LIBS=`find ./lib -name '*.jar' -printf '%p:'`
PC_LIBS=`find ./pc-lib -name '*.jar' -printf '%p:'`
export CLASSPATH="$COMMON_LIBS$PC_LIBS./pc-build"

java uk.ac.cam.dbs.tools.DBSChat $@
